export const TRANSACTION_GAS_PRICE = 0.01;

export const USDT_MASTER = 'EQDnRHbK5vJBLQyAnS6V8XNoRerCebnn9A2FlVlHtFVLFGZ-'

export const CONTRACT_ADDRESS_MOCK = 'EQD_PhuKItHXw3JCp8BOP6u5zUOQ0qBRAZuR61IRZOr49JY2'

export const SENDER_WALLET_MOCK = '0QAnZtQHeq2wCSUqN1Bmoh66S65jDEBSQhWoKScQFwbM5au-'
